# Generated by Django 4.1.7 on 2023-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(default='house.png', null=True, upload_to=''),
        ),
    ]
