# Generated by Django 4.1.7 on 2023-06-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='avatar',
            new_name='image',
        ),
    ]
