# Generated by Django 4.1.7 on 2023-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_avatar_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='house.PNG', null=True, upload_to=''),
        ),
    ]
