# Generated by Django 4.1.7 on 2023-06-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_amount_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
