# Generated by Django 4.1.7 on 2023-06-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
